import { NextResponse } from "next/server";
import { prisma } from "@/lib/db";
import { requireUser } from "@/lib/auth";
import { getCompanyProfile, getScoringWeights } from "@/services/dashboard/service";
import { scoreProject } from "@/services/scoring/projectScoring";
import { parseJsonArray, parseJsonObject, toJson } from "@/lib/utils";

/** Re-score / rank all company projects with current weights. */
export async function POST() {
  try {
    const user = await requireUser();
    if (!user?.companyId) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const company = await getCompanyProfile(user.companyId);
    const weights = await getScoringWeights(user.companyId);
    if (!company) {
      return NextResponse.json({ error: "Company not found" }, { status: 404 });
    }

    const projects = await prisma.project.findMany({
      where: { companyId: user.companyId },
      include: { ngo: true },
    });

    const ranked: {
      id: string;
      name: string;
      overallScore: number;
      recommendationLevel: string;
      dimensions: Record<string, unknown>;
    }[] = [];

    for (const p of projects) {
      const bens = parseJsonObject(p.beneficiaries, { count: 0, groups: [] as string[] });
      const scored = scoreProject(
        {
          name: p.name,
          category: p.category,
          description: p.description,
          geography: parseJsonArray(p.geography),
          beneficiaryCount: bens.count,
          beneficiaryGroups: bens.groups,
          requestedBudget: p.requestedBudget,
          durationMonths: p.durationMonths,
          outcomes: parseJsonArray(p.targetOutcomes),
          risks: [],
          requiredExpertise: parseJsonArray(p.requiredExpertise),
          dataCompleteness: 0.85,
        },
        company,
        p.ngo?.executionReliability
          ? {
              executionReliability: p.ngo.executionReliability,
              projectCount: p.ngo.projectCount ?? 0,
            }
          : undefined,
        weights
      );

      await prisma.project.update({
        where: { id: p.id },
        data: {
          overallScore: scored.overallScore,
          recommendationLevel: scored.recommendationLevel,
        },
      });

      await prisma.projectScore.create({
        data: {
          projectId: p.id,
          overallScore: scored.overallScore,
          socialImpact: scored.dimensions.socialImpact.score,
          executionReliability: scored.dimensions.executionReliability.score,
          companyAlignment: scored.dimensions.companyAlignment.score,
          communityBrandResonance: scored.dimensions.communityBrandResonance.score,
          costRiskEfficiency: scored.dimensions.costRiskEfficiency.score,
          overallConfidence: scored.confidence,
          explanation: toJson({
            overall: scored.explanation,
            dimensions: scored.dimensions,
            contributions: scored.contributions,
            recommendationLevel: scored.recommendationLevel,
          }),
          weights: toJson(weights),
        },
      });

      ranked.push({
        id: p.id,
        name: p.name,
        overallScore: scored.overallScore,
        recommendationLevel: scored.recommendationLevel,
        dimensions: scored.dimensions,
      });
    }

    ranked.sort((a, b) => b.overallScore - a.overallScore);

    return NextResponse.json({
      ranked,
      weights,
      note: "Scores generated by deterministic KellyOS engine. Human review required.",
    });
  } catch (e) {
    console.error(e);
    return NextResponse.json({ error: "Unable to run prioritization." }, { status: 500 });
  }
}

export async function GET() {
  try {
    const user = await requireUser();
    if (!user?.companyId) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }
    const projects = await prisma.project.findMany({
      where: { companyId: user.companyId },
      include: { scores: { orderBy: { createdAt: "desc" }, take: 1 } },
      orderBy: { overallScore: "desc" },
    });
    return NextResponse.json({ projects });
  } catch {
    return NextResponse.json({ error: "Unable to load prioritization." }, { status: 500 });
  }
}
